##################################################
# Makefile intro
#
# - A makefile is nothing more than
#   	targer: prerequisites ...
#   		recipe
#
# - Targets are labels if that tells make what you 
#   want to start running in order to build your 
#   project. 
# - Prerequisites are items that each specific
#   target requires to run.
# - Recipes are the actual commands if you will 
#   that you want make to run.
#################################################

all: main.c
	gcc -o test_program main.c -I.
